
- hosts: webservers
  vars:
    Tomcat_download: http://redrockdigimark.com/apachemirror/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.tar.gz
    Tomcat_name: "apache-8-tomcat"
    download_folder: "/usr/bin"
    Tomcat_archive: "{{download_folder}}/apache-tomcat-8.5.11.tar.gz"
    Tomcat_alias: Tomcat-8


  tasks:

  - file:
      path: "{{download_folder}}"
      owner: root
      mode: 0776
  - name: Download Tomcat
    get_url: 'url={{Tomcat_download}} dest={{download_folder}}'

  - name: Download and unpack tomcat
    unarchive:
      src: "{{download_folder}}/apache-tomcat-8.5.11.tar.gz"
      dest: "{{download_folder}}"
      copy: no
      owner: root
      mode: 0755
      list_files: true
      creates: "{{Tomcat_name}}"


  - name: Fix ownership
    file: "state=directory path={{download_folder}}/{{Tomcat_name}}  owner=root recurse=yes"

  - name: Firewall settings
    firewalld: zone=public port=8080/tcp permanent=true state=enabled

  - shell: firewall-cmd --reload
